es:
   host: ${ES_HOST:localhost}
   httpports: ${ES_HTTP_PORTS:9200}
   isSecured: ${ES_XPAK_INSTALLED:false}
   userName: ${ES_USERNAME:elastic}
   password: ${ES_PASSWORD:password}
   
logging:
   level:
      com:
         bluecedar.*: debug
   pattern:
      console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger %X{userID} - %msg%n"
      
      
spring:
   banner:
      location: classpath:banner.txt
      
server:
   port: ${SERVER_PORT:8080}
   
bluecedar:
  security:
    secured-paths:
      - /analyzer/**


